const statusEl = document.getElementById("status");
const outputEl = document.getElementById("output");
const copyBtn = document.getElementById("copy");
const downloadBtn = document.getElementById("download");

let currentSessdata = "";

function setStatus(message) {
  statusEl.textContent = message;
}

function mask(value) {
  if (!value) return "";
  if (value.length <= 12) return "*".repeat(value.length);
  return `${value.slice(0, 6)}...${value.slice(-6)}`;
}

function netscapeCookie(sessdata) {
  const expires = Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 30;
  return [
    "# Netscape HTTP Cookie File",
    "# Generated by Bilibili SESSDATA Helper.",
    `.bilibili.com\tTRUE\t/\tFALSE\t${expires}\tSESSDATA\t${sessdata}`,
    `www.bilibili.com\tFALSE\t/\tFALSE\t${expires}\tSESSDATA\t${sessdata}`,
    ""
  ].join("\n");
}

async function readSessdata() {
  try {
    const cookie = await chrome.cookies.get({
      url: "https://www.bilibili.com/",
      name: "SESSDATA"
    });

    if (!cookie || !cookie.value) {
      currentSessdata = "";
      outputEl.value = "";
      setStatus("没有读到 SESSDATA。请先在当前浏览器登录 bilibili.com，再刷新此弹窗。");
      return;
    }

    currentSessdata = cookie.value.replaceAll("\\_", "_");
    outputEl.value = currentSessdata;
    setStatus(`已读取 SESSDATA：${mask(currentSessdata)} (${currentSessdata.length} 字符)`);
  } catch (error) {
    currentSessdata = "";
    outputEl.value = "";
    setStatus(`读取失败：${error && error.message ? error.message : String(error)}`);
  }
}

copyBtn.addEventListener("click", async () => {
  if (!currentSessdata) {
    setStatus("没有可复制的 SESSDATA。");
    return;
  }
  await navigator.clipboard.writeText(currentSessdata);
  setStatus("已复制 SESSDATA。");
});

downloadBtn.addEventListener("click", () => {
  if (!currentSessdata) {
    setStatus("没有可下载的 SESSDATA。");
    return;
  }
  const blob = new Blob([netscapeCookie(currentSessdata)], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  chrome.downloads.download({
    url,
    filename: "bilibili.txt",
    saveAs: true
  });
  setStatus("已发起下载，建议保存为 E:\\Projects\\ai\\video-sub-md\\cookies\\bilibili.txt");
});

readSessdata();
